# Generated by Django 3.2.9 on 2021-11-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_bookspopularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pageno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookspopularity',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
