# Generated by Django 3.2.9 on 2021-11-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211102_0516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': (('can_edit_title', 'can edit title on books'), ('can_add_pageno', 'can add pageno on books'))},
        ),
    ]
