# Generated by Django 3.2.9 on 2021-11-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_books_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': (('can-edit-title', 'can edit title on books'), ('can-add-pageno', 'can add pageno on books'))},
        ),
    ]
