# Generated by Django 3.2.9 on 2021-11-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_books_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': (('canedittitle', 'can edit title on books'), ('canaddpageno', 'can add pageno on books'))},
        ),
    ]
